import io.spring.gradle.dependencymanagement.dsl.DependencyManagementExtension

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.anasoid.jmeter.cloud.kotlin-library-conventions")
    id("org.anasoid.jmeter.cloud.kotlin-boot-conventions")

    //spring
    id("org.springframework.boot") version "3.1.1" apply false
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("plugin.spring") version "1.8.22"
}

apply(plugin = "io.spring.dependency-management")
the<DependencyManagementExtension>().apply {
    imports {
        mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
    }
}


dependencies {
    api(project(":jmeter-cloud-utilities"))
    implementation("jakarta.validation:jakarta.validation-api")
}
